-- +goose Up
CREATE TABLE IF NOT EXISTS white_list (
     sub_net CIDR PRIMARY KEY,
     date_create TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS black_list (
     sub_net CIDR PRIMARY KEY,
     date_create TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- +goose Down
DROP TABLE IF EXISTS white_list;
DROP TABLE IF EXISTS black_list;
